# boards are ordered by priority so that when monitoring a build developers get feedback on the important ones first.
env:
  - RUNTESTS=True
  - PUBLISHMETA=True
  - PUBLISHDOCS=True
  - TARGET=SPRACINGF3MINI
  - TARGET=SPRACINGF3EVO
  - TARGET=SPRACINGF3
  - TARGET=SPRACINGF3OSD
  - TARGET=SPRACINGF1OSD
  - TARGET=NAZE
  - TARGET=CC3D
  - TARGET=CJMCU
  - TARGET=SPARKY
  - TARGET=COLIBRI_RACE
  - TARGET=LUX_RACE  
  - TARGET=MOTOLAB
  - TARGET=RMDO
  - TARGET=ALIENFLIGHTF3
  - TARGET=ALIENFLIGHTF1
  - TARGET=STM32F3DISCOVERY
  - TARGET=PORT103R
  - TARGET=EUSTM32F103RC
  - TARGET=CHEBUZZF3
  - TARGET=OLIMEXINO
  - TARGET=IRCFUSIONF3
  - TARGET=RCEXPLORERF3

# use new docker environment
sudo: false

addons:
  apt:
    packages:
      - build-essential
      - git
      - libc6-i386
      - zlib1g-dev
      - libssl-dev
      - wkhtmltopdf
      - libxml2-dev
      - libxslt-dev

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

before_install:
  - curl --retry 10 --retry-max-time 120 -L "https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/gcc-arm-none-eabi-5_4-2016q2-20160622-linux.tar.bz2" | tar xfj -

install:
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q2/bin

before_script: arm-none-eabi-gcc --version
script: ./.travis.sh

cache: apt

notifications:
  irc: "chat.freenode.net#cleanflight"
  use_notice: true
  skip_join: true
