name: Release

on:
  release:
    types: [published]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      release_build: true

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v5

      - name: List downloaded artifacts
        run: ls -al

      - name: Attach assets to release
        run: |
          set -x
          ASSETS=()
          for asset in ./*/*.hex ./*/*.uf2; do
            if [ -f "$asset" ]; then
              ASSETS+=("$asset")
              echo "$asset"
            fi
          done
          TAG_NAME="${GITHUB_REF##*/}"
          gh release upload "${TAG_NAME}" "${ASSETS[@]}" -R "${GITHUB_REPOSITORY}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
